version: "3.1"

services:

  db:
    container_name: skos-postgres
    image: registry-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - arcnet
    environment:
      - POSTGRES_USER=vrasidas
      - POSTGRES_PASS=paparia
      - POSTGRES_DB=registry
    restart: unless-stopped

  jms:
    container_name: jms
    image: rmohr/activemq:5.14.0-alpine
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - arcnet
    restart: unless-stopped

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata_new:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped


volumes:
  esdata_new:
    driver: local
  pgdata:
    driver: local

networks:
  arcnet:
    driver: bridge

